[project]
name = "rbc-project-physics"
version = "0.1.0"
description = "Robocute Official Physics Startup Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
]
